#!/usr/bin/env python3
"""Regression tests for the direct-dependency lock checker."""

import sys
import tempfile
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from check_lock import (  # noqa: E402
    LockCheckError,
    canonical_lock_blocks,
    require_matching_closure,
    validate_lock,
)


class LockCheckerTests(unittest.TestCase):
    def validate(self, source, lock):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            source_path = root / "requirements.txt"
            lock_path = root / "requirements.lock"
            source_path.write_text(source, encoding="utf-8")
            lock_path.write_text(lock, encoding="utf-8")
            validate_lock(source_path, lock_path)

    def compare_closure(self, checked, generated):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            checked_path = root / "requirements.lock"
            generated_path = root / "generated.lock"
            checked_path.write_text(checked, encoding="utf-8")
            generated_path.write_text(generated, encoding="utf-8")
            return canonical_lock_blocks(checked_path), canonical_lock_blocks(generated_path)

    def test_accepts_equal_checked_and_resolver_closures(self):
        hash_a = "a" * 64
        checked, generated = self.compare_closure(
            f"""alpha==1.0.0 \\
    --hash=sha256:{hash_a}
    # via -r requirements.txt
""",
            f"""# This file was autogenerated by uv\nalpha==1.0.0 \\
    --hash=sha256:{hash_a}
""",
        )
        require_matching_closure(checked, generated)

    def test_rejects_hash_valid_orphan_from_resolver_closure(self):
        hash_a = "a" * 64
        idna_wheel_hash = "946d195a0d259cbba61165e88e65941f16e9b36ea6ddb97f00452bae8b1287d3"
        checked, generated = self.compare_closure(
            f"""alpha==1.0.0 \\
    --hash=sha256:{hash_a}
    # via -r requirements.txt
idna==3.10 \\
    --hash=sha256:{idna_wheel_hash}
    # via cryptography
""",
            f"""alpha==1.0.0 \\
    --hash=sha256:{hash_a}
""",
        )
        with self.assertRaisesRegex(LockCheckError, "resolver closure"):
            require_matching_closure(checked, generated)

    def test_accepts_single_and_multiline_direct_provenance(self):
        hash_a = "a" * 64
        hash_b = "b" * 64
        hash_c = "c" * 64
        self.validate(
            "alpha==1.0.0\nbravo==2.0.0\n",
            f"""alpha==1.0.0 \\
    --hash=sha256:{hash_a}
    # via -r requirements.txt
bravo==2.0.0 \\
    --hash=sha256:{hash_b} \\
    --hash=sha256:{hash_c}
    # via
    #   -r requirements.txt
transitive==3.0.0 ; implementation_name != 'PyPy' \\
    --hash=sha256:{hash_c}
    # via alpha
""",
        )

    def test_rejects_marker_bearing_source_direct(self):
        with self.assertRaisesRegex(LockCheckError, "exact unconditional"):
            self.validate("alpha==1.0.0 ; python_version >= '3.12'\n", "")

    def test_rejects_direct_source_options(self):
        with self.assertRaisesRegex(LockCheckError, "exact unconditional"):
            self.validate("--only-binary=:all:\nalpha==1.0.0\n", "")

    def test_rejects_marker_bearing_direct_lock_block(self):
        hash_a = "a" * 64
        with self.assertRaisesRegex(LockCheckError, "unconditional"):
            self.validate(
                "alpha==1.0.0\n",
                f"""alpha==1.0.0 ; python_version >= '3.12' \\
    --hash=sha256:{hash_a}
    # via -r requirements.txt
""",
            )

    def test_rejects_detached_hash_continuations(self):
        hash_a = "a" * 64
        hash_b = "b" * 64
        with self.assertRaisesRegex(LockCheckError, "header.*backslash"):
            self.validate(
                "alpha==1.0.0\n",
                f"""alpha==1.0.0
    --hash=sha256:{hash_a}
    # via -r requirements.txt
""",
            )
        with self.assertRaisesRegex(LockCheckError, "intermediate hash.*backslash"):
            self.validate(
                "alpha==1.0.0\n",
                f"""alpha==1.0.0 \\
    --hash=sha256:{hash_a}
    --hash=sha256:{hash_b}
    # via -r requirements.txt
""",
            )

    def test_rejects_provenance_before_or_between_hashes(self):
        hash_a = "a" * 64
        hash_b = "b" * 64
        with self.assertRaisesRegex(LockCheckError, "after provenance"):
            self.validate(
                "alpha==1.0.0\n",
                f"""alpha==1.0.0 \\
    # via -r requirements.txt
    --hash=sha256:{hash_a}
""",
            )
        with self.assertRaisesRegex(LockCheckError, "after provenance"):
            self.validate(
                "alpha==1.0.0\n",
                f"""alpha==1.0.0 \\
    --hash=sha256:{hash_a} \\
    # via -r requirements.txt
    --hash=sha256:{hash_b}
""",
            )

    def test_rejects_non_exact_project_names_and_versions_in_source_and_lock(self):
        hash_a = "a" * 64
        invalid_requirements = (
            "alpha-==1.0",
            "alpha.==1.0",
            "alpha==@url",
            "alpha==1.*",
            "alpha===1.0",
            "alpha==1.0,!=2.0",
        )
        valid_lock = f"""alpha==1.0 \\
    --hash=sha256:{hash_a}
    # via -r requirements.txt
"""
        for requirement in invalid_requirements:
            with self.subTest(requirement=requirement, location="source"):
                with self.assertRaisesRegex(LockCheckError, "exact immutable"):
                    self.validate(requirement + "\n", valid_lock)
            with self.subTest(requirement=requirement, location="lock"):
                with self.assertRaisesRegex(LockCheckError, "exact immutable"):
                    self.validate(
                        "alpha==1.0\n",
                        f"""{requirement} \\
    --hash=sha256:{hash_a}
    # via -r requirements.txt
""",
                    )

    def test_accepts_only_whitespace_delimited_source_comments(self):
        hash_a = "a" * 64
        lock = f"""alpha==1.0 \\
    --hash=sha256:{hash_a}
    # via -r requirements.txt
"""
        self.validate("\n# full-line comment\nalpha==1.0 # inline comment\n", lock)
        for suffix in ("#garbage", "#@https://attacker.invalid/x"):
            with self.subTest(suffix=suffix):
                with self.assertRaisesRegex(LockCheckError, "exact immutable"):
                    self.validate("alpha==1.0" + suffix + "\n", lock)

    def test_rejects_pip_active_top_level_and_indented_lock_content(self):
        hash_a = "a" * 64
        valid_lock = f"""alpha==1.0 \\
    --hash=sha256:{hash_a}
    # via -r requirements.txt
"""
        directives = (
            "-r /definitely/missing/extra.txt",
            "-c /definitely/missing/constraints.txt",
            "--extra-index-url https://attacker.invalid/simple",
            "--trusted-host attacker.invalid",
            "https://attacker.invalid/pkg.whl",
            "./local-package.whl",
        )
        for directive in directives:
            with self.subTest(directive=directive, location="top-level"):
                with self.assertRaisesRegex(LockCheckError, "lock"):
                    self.validate("alpha==1.0\n", valid_lock + directive + "\n")
            with self.subTest(directive=directive, location="indented"):
                with self.assertRaisesRegex(LockCheckError, "lock"):
                    self.validate(
                        "alpha==1.0\n",
                        valid_lock
                        + f"""transitive==2.0 \\
    {directive}
    # via transitive
""",
                    )

    def test_rejects_duplicate_direct_blocks(self):
        hash_a = "a" * 64
        with self.assertRaisesRegex(LockCheckError, "duplicate direct"):
            self.validate(
                "alpha==1.0.0\n",
                f"""alpha==1.0.0 \\
    --hash=sha256:{hash_a}
    # via -r requirements.txt
alpha==1.0.0 \\
    --hash=sha256:{hash_a}
    # via
    #   -r requirements.txt
""",
            )

    def test_rejects_missing_extra_and_version_drift(self):
        hash_a = "a" * 64
        hash_b = "b" * 64
        with self.assertRaisesRegex(LockCheckError, "missing from lock: alpha"):
            self.validate("alpha==1.0.0\n", "")
        with self.assertRaisesRegex(LockCheckError, "absent from source: bravo"):
            self.validate("", f"""bravo==2.0.0 \\
    --hash=sha256:{hash_b}
    # via -r requirements.txt
""")
        with self.assertRaisesRegex(LockCheckError, "alpha: requirements.txt=1.0.0, requirements.lock=2.0.0"):
            self.validate("alpha==1.0.0\n", f"""alpha==2.0.0 \\
    --hash=sha256:{hash_a}
    # via -r requirements.txt
""")

    def test_rejects_detached_provenance_after_a_blank(self):
        hash_a = "a" * 64
        with self.assertRaisesRegex(LockCheckError, "detached"):
            self.validate(
                "alpha==1.0.0\n",
                f"""alpha==1.0.0 \\
    --hash=sha256:{hash_a}

    # via -r requirements.txt
""",
            )

    def test_rejects_ambiguous_multiline_provenance(self):
        hash_a = "a" * 64
        with self.assertRaisesRegex(LockCheckError, "ambiguous"):
            self.validate(
                "alpha==1.0.0\n",
                f"""alpha==1.0.0 \\
    --hash=sha256:{hash_a}
    # via
    #   another-dependency
    #   -r requirements.txt
""",
            )

    def test_rejects_hashless_and_malformed_direct_blocks(self):
        with self.assertRaisesRegex(LockCheckError, "no hashes"):
            self.validate(
                "alpha==1.0.0\n",
                """alpha==1.0.0 \\
    # via -r requirements.txt
""",
            )
        with self.assertRaisesRegex(LockCheckError, "malformed hash"):
            self.validate(
                "alpha==1.0.0\n",
                """alpha==1.0.0 \\
    --hash=sha256:not-a-valid-hash
    # via -r requirements.txt
""",
            )


if __name__ == "__main__":
    unittest.main()
