// Package provision is the curated, exported surface an operator uses to
// provision a Snagline deployment from outside this module: generating and
// custody-managing Ed25519 signing keys, and constructing, signing, and
// verifying a root-authorized ssp.registry.v1 envelope.
//
// Every exported entry point is a thin, fail-closed wrapper over
// internal/identity, internal/registry, and internal/ssp. This package adds
// no new authority, trust, or wire semantics of its own; internal/ssp and
// internal/registry remain the sole owners of the frozen SSP contract and of
// what a verified registry means.
package provision

import (
	"crypto/ed25519"
	"crypto/rand"
	"crypto/x509"
	"encoding/pem"
	"errors"
	"fmt"
	"sync"

	"github.com/avivsinai/snagline/internal/identity"
)

// SigningKey is an Ed25519 signing key together with the private-key custody
// state needed to persist it exactly once, at the moment it was generated.
//
// A SigningKey obtained from GenerateSigningKey can be written to disk with
// WriteTo, once. A SigningKey obtained from LoadSigningKey carries no
// exportable private material — it can only be used to sign — because it was
// already read from custody-controlled storage and re-exporting it would
// duplicate the operator's single point of custody for that key.
//
// SigningKey is a value type, but its custody state is not copied with it:
// the state lives behind a shared pointer, so copying a SigningKey, or using
// the same one from several goroutines, still yields exactly one successful
// WriteTo across every copy.
type SigningKey struct {
	custody *custody
	signing identity.Ed25519SigningKey
}

// custody is the write-once private-key state that a SigningKey and every
// copy of it share. Holding it behind a pointer is what makes the
// one-custody-point rule an invariant rather than a convention: copying a
// SigningKey value copies this pointer, not the state behind it, so
// `copied := key` cannot buy a second write.
type custody struct {
	mu      sync.Mutex
	written bool
	private ed25519.PrivateKey
}

// GenerateSigningKey creates a fresh Ed25519 key pair for use as a registry
// root, edge, or dispatcher signing key. The returned key can both sign and
// be persisted with WriteTo.
func GenerateSigningKey() (SigningKey, error) {
	_, private, err := ed25519.GenerateKey(rand.Reader)
	if err != nil {
		return SigningKey{}, fmt.Errorf("provision: generate ed25519 key: %w", err)
	}
	signing, err := identity.NewEd25519SigningKey(private)
	if err != nil {
		return SigningKey{}, fmt.Errorf("provision: wrap generated signing key: %w", err)
	}
	return SigningKey{
		custody: &custody{private: append(ed25519.PrivateKey(nil), private...)},
		signing: signing,
	}, nil
}

// LoadSigningKey reads a previously provisioned Ed25519 signing key from a
// PKCS8 PEM file. It fails closed: path must be an absolute, clean path with
// no symlink at the leaf or at any directory above it (see WriteTo), the file
// must be a current-user-owned regular file with no group or other permission
// bits set, and it must contain exactly one "PRIVATE KEY" PEM block encoding
// an Ed25519 key.
//
// The returned key can sign but cannot be re-persisted with WriteTo; see
// SigningKey.
func LoadSigningKey(path string) (SigningKey, error) {
	raw, err := readPrivateFile(path)
	if err != nil {
		return SigningKey{}, err
	}
	signing, err := identity.ParseEd25519SigningKeyPEM(raw)
	if err != nil {
		return SigningKey{}, err
	}
	return SigningKey{signing: signing}, nil
}

// PublicKey returns the key's Ed25519 public key.
func (k SigningKey) PublicKey() (ed25519.PublicKey, error) {
	return k.signing.PublicKey()
}

// WriteTo persists the key generated by GenerateSigningKey as a PKCS8
// "PRIVATE KEY" PEM file at an absolute path, fail-closed:
//
//   - path must be absolute and clean.
//   - no component of path may be a symlink. WriteTo opens each directory in
//     turn with O_NOFOLLOW rather than handing the whole pathname to the
//     kernel, so a symlinked parent cannot redirect the key somewhere the
//     caller never named. On a platform whose system directories are
//     themselves symlinks — macOS /etc, /var, and /tmp all are — pass the
//     already-resolved path.
//   - path must not already exist. WriteTo never overwrites or follows an
//     existing file or symlink at that location, so a caller can never lose
//     key material to a silent overwrite or a symlink race.
//   - the file is created with, and left at, exactly 0600 permissions.
//   - on success the file's contents and the directory entry naming it are
//     both flushed to stable storage, so a provisioned key survives a crash
//     or power loss rather than silently vanishing.
//   - it succeeds at most once per generated key, and custody is spent the
//     moment the file is created rather than when the write completes. A
//     failure before creation (a bad path, an occupied path) leaves the key
//     writable. A failure after creation spends custody, so the caller must
//     regenerate: retrying elsewhere could leave two artifacts for one key.
//     A post-create failure leaves its artifact in place: POSIX cannot safely
//     condition an unlink on the inode it checked. The caller must treat an
//     artifact as potentially present. Once spent, every later
//     attempt fails, including from a copy of the SigningKey value and from
//     a concurrent goroutine.
//
// A key obtained from LoadSigningKey has no private material to persist and
// WriteTo always fails for it.
func (k SigningKey) WriteTo(path string) error {
	if k.custody == nil {
		return errors.New("provision: signing key has no private material to write (was it loaded rather than generated?)")
	}
	return k.custody.writeTo(path)
}

func (c *custody) writeTo(path string) error {
	c.mu.Lock()
	defer c.mu.Unlock()
	if c.written {
		return errors.New("provision: signing key private material has already been written; a generated key has exactly one point of custody")
	}
	der, err := x509.MarshalPKCS8PrivateKey(c.private)
	if err != nil {
		return fmt.Errorf("provision: marshal signing key: %w", err)
	}
	block := pem.EncodeToMemory(&pem.Block{Type: "PRIVATE KEY", Bytes: der})
	created, err := writePrivateFile(path, block)
	if created {
		// Custody is spent the moment a key file reaches the filesystem, not
		// when the write finishes cleanly. A post-create failure leaves its
		// artifact in place, so the operator must regenerate rather than retry
		// at another path: retrying would risk a second artifact for a key
		// meant to have exactly one.
		c.written = true
	}
	return err
}

// MarshalVerifyingKeyPEM PEM-encodes an Ed25519 public key as a PKIX
// "PUBLIC KEY" block, for distribution to the deployment components (edge,
// control, projector) that must verify envelopes authored by the
// corresponding signing key. It performs encoding only: the verifying key is
// not secret, and where it is written and with what permissions is a
// deployment-topology decision the caller owns.
func MarshalVerifyingKeyPEM(publicKey ed25519.PublicKey) ([]byte, error) {
	if len(publicKey) != ed25519.PublicKeySize {
		return nil, fmt.Errorf("provision: verifying key must be %d bytes", ed25519.PublicKeySize)
	}
	der, err := x509.MarshalPKIXPublicKey(publicKey)
	if err != nil {
		return nil, fmt.Errorf("provision: marshal verifying key: %w", err)
	}
	return pem.EncodeToMemory(&pem.Block{Type: "PUBLIC KEY", Bytes: der}), nil
}
